package stubs.cart;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-04-07T15:20:57.667+02:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/tcf/cart", name = "CartWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface CartWebService {

    @WebMethod
    @RequestWrapper(localName = "validate", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/tcf/cart", className = "stubs.cart.Validate")
    @ResponseWrapper(localName = "validateResponse", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/tcf/cart", className = "stubs.cart.ValidateResponse")
    @WebResult(name = "order_id", targetNamespace = "")
    public java.lang.String validate(
        @WebParam(name = "customer_name", targetNamespace = "")
        java.lang.String customerName
    ) throws PaymentException_Exception, UnknownCustomerException_Exception, EmptyCartException_Exception;

    @WebMethod
    @RequestWrapper(localName = "removeItemToCustomerCart", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/tcf/cart", className = "stubs.cart.RemoveItemToCustomerCart")
    @ResponseWrapper(localName = "removeItemToCustomerCartResponse", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/tcf/cart", className = "stubs.cart.RemoveItemToCustomerCartResponse")
    public void removeItemToCustomerCart(
        @WebParam(name = "customer_name", targetNamespace = "")
        java.lang.String customerName,
        @WebParam(name = "item", targetNamespace = "")
        stubs.cart.Item item
    ) throws UnknownCustomerException_Exception;

    @WebMethod
    @RequestWrapper(localName = "addItemToCustomerCart", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/tcf/cart", className = "stubs.cart.AddItemToCustomerCart")
    @ResponseWrapper(localName = "addItemToCustomerCartResponse", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/tcf/cart", className = "stubs.cart.AddItemToCustomerCartResponse")
    public void addItemToCustomerCart(
        @WebParam(name = "customer_name", targetNamespace = "")
        java.lang.String customerName,
        @WebParam(name = "item", targetNamespace = "")
        stubs.cart.Item item
    ) throws UnknownCustomerException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getCustomerCartContents", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/tcf/cart", className = "stubs.cart.GetCustomerCartContents")
    @ResponseWrapper(localName = "getCustomerCartContentsResponse", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/tcf/cart", className = "stubs.cart.GetCustomerCartContentsResponse")
    @WebResult(name = "cart_contents", targetNamespace = "")
    public java.util.List<stubs.cart.Item> getCustomerCartContents(
        @WebParam(name = "customer_name", targetNamespace = "")
        java.lang.String customerName
    ) throws UnknownCustomerException_Exception;
}
