
package stubs.cart;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-04-07T15:20:57.661+02:00
 * Generated source version: 3.1.10
 */

@WebFault(name = "EmptyCartException", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/tcf/cart")
public class EmptyCartException_Exception extends Exception {
    
    private stubs.cart.EmptyCartException emptyCartException;

    public EmptyCartException_Exception() {
        super();
    }
    
    public EmptyCartException_Exception(String message) {
        super(message);
    }
    
    public EmptyCartException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public EmptyCartException_Exception(String message, stubs.cart.EmptyCartException emptyCartException) {
        super(message);
        this.emptyCartException = emptyCartException;
    }

    public EmptyCartException_Exception(String message, stubs.cart.EmptyCartException emptyCartException, Throwable cause) {
        super(message, cause);
        this.emptyCartException = emptyCartException;
    }

    public stubs.cart.EmptyCartException getFaultInfo() {
        return this.emptyCartException;
    }
}
