
package stubs.cart;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-04-07T15:20:57.634+02:00
 * Generated source version: 3.1.10
 */

@WebFault(name = "PaymentException", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/tcf/cart")
public class PaymentException_Exception extends Exception {
    
    private stubs.cart.PaymentException paymentException;

    public PaymentException_Exception() {
        super();
    }
    
    public PaymentException_Exception(String message) {
        super(message);
    }
    
    public PaymentException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public PaymentException_Exception(String message, stubs.cart.PaymentException paymentException) {
        super(message);
        this.paymentException = paymentException;
    }

    public PaymentException_Exception(String message, stubs.cart.PaymentException paymentException, Throwable cause) {
        super(message, cause);
        this.paymentException = paymentException;
    }

    public stubs.cart.PaymentException getFaultInfo() {
        return this.paymentException;
    }
}
