
package stubs.cart;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-04-07T15:20:57.657+02:00
 * Generated source version: 3.1.10
 */

@WebFault(name = "UnknownCustomerException", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/tcf/cart")
public class UnknownCustomerException_Exception extends Exception {
    
    private stubs.cart.UnknownCustomerException unknownCustomerException;

    public UnknownCustomerException_Exception() {
        super();
    }
    
    public UnknownCustomerException_Exception(String message) {
        super(message);
    }
    
    public UnknownCustomerException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public UnknownCustomerException_Exception(String message, stubs.cart.UnknownCustomerException unknownCustomerException) {
        super(message);
        this.unknownCustomerException = unknownCustomerException;
    }

    public UnknownCustomerException_Exception(String message, stubs.cart.UnknownCustomerException unknownCustomerException, Throwable cause) {
        super(message, cause);
        this.unknownCustomerException = unknownCustomerException;
    }

    public stubs.cart.UnknownCustomerException getFaultInfo() {
        return this.unknownCustomerException;
    }
}
