
package stubs.customerCare;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-04-07T15:20:57.816+02:00
 * Generated source version: 3.1.10
 */

@WebFault(name = "AlreadyExistingCustomerException", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/tcf/customer-care")
public class AlreadyExistingCustomerException_Exception extends Exception {
    
    private stubs.customerCare.AlreadyExistingCustomerException alreadyExistingCustomerException;

    public AlreadyExistingCustomerException_Exception() {
        super();
    }
    
    public AlreadyExistingCustomerException_Exception(String message) {
        super(message);
    }
    
    public AlreadyExistingCustomerException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public AlreadyExistingCustomerException_Exception(String message, stubs.customerCare.AlreadyExistingCustomerException alreadyExistingCustomerException) {
        super(message);
        this.alreadyExistingCustomerException = alreadyExistingCustomerException;
    }

    public AlreadyExistingCustomerException_Exception(String message, stubs.customerCare.AlreadyExistingCustomerException alreadyExistingCustomerException, Throwable cause) {
        super(message, cause);
        this.alreadyExistingCustomerException = alreadyExistingCustomerException;
    }

    public stubs.customerCare.AlreadyExistingCustomerException getFaultInfo() {
        return this.alreadyExistingCustomerException;
    }
}
