package stubs.customerCare;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-04-07T15:20:57.820+02:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/tcf/customer-care", name = "CustomerCareService")
@XmlSeeAlso({ObjectFactory.class})
public interface CustomerCareService {

    @WebMethod
    @RequestWrapper(localName = "track", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/tcf/customer-care", className = "stubs.customerCare.Track")
    @ResponseWrapper(localName = "trackResponse", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/tcf/customer-care", className = "stubs.customerCare.TrackResponse")
    @WebResult(name = "status", targetNamespace = "")
    public stubs.customerCare.OrderStatus track(
        @WebParam(name = "order_id", targetNamespace = "")
        java.lang.String orderId
    ) throws UnknownOrderId_Exception;

    @WebMethod
    @RequestWrapper(localName = "listAllRecipes", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/tcf/customer-care", className = "stubs.customerCare.ListAllRecipes")
    @ResponseWrapper(localName = "listAllRecipesResponse", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/tcf/customer-care", className = "stubs.customerCare.ListAllRecipesResponse")
    @WebResult(name = "recipes", targetNamespace = "")
    public java.util.List<stubs.customerCare.Cookies> listAllRecipes();

    @WebMethod
    @RequestWrapper(localName = "register", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/tcf/customer-care", className = "stubs.customerCare.Register")
    @ResponseWrapper(localName = "registerResponse", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/tcf/customer-care", className = "stubs.customerCare.RegisterResponse")
    public void register(
        @WebParam(name = "customer_name", targetNamespace = "")
        java.lang.String customerName,
        @WebParam(name = "credit_card_number", targetNamespace = "")
        java.lang.String creditCardNumber
    ) throws AlreadyExistingCustomerException_Exception;
}
