package stubs.customerCare;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-04-07T15:20:57.824+02:00
 * Generated source version: 3.1.10
 * 
 */
@WebServiceClient(name = "CustomerCareServiceImplService", 
                  wsdlLocation = "file:/home/matt/workspace/devops-polytech/2_cookie_factory_splitted/client/src/main/resources/CustomerCareWS.wsdl",
                  targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/tcf/customer-care") 
public class CustomerCareServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.polytech.unice.fr/si/4a/isa/tcf/customer-care", "CustomerCareServiceImplService");
    public final static QName CustomerCareServiceImplPort = new QName("http://www.polytech.unice.fr/si/4a/isa/tcf/customer-care", "CustomerCareServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/matt/workspace/devops-polytech/2_cookie_factory_splitted/client/src/main/resources/CustomerCareWS.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CustomerCareServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/matt/workspace/devops-polytech/2_cookie_factory_splitted/client/src/main/resources/CustomerCareWS.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CustomerCareServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CustomerCareServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomerCareServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public CustomerCareServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CustomerCareServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CustomerCareServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns CustomerCareService
     */
    @WebEndpoint(name = "CustomerCareServiceImplPort")
    public CustomerCareService getCustomerCareServiceImplPort() {
        return super.getPort(CustomerCareServiceImplPort, CustomerCareService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomerCareService
     */
    @WebEndpoint(name = "CustomerCareServiceImplPort")
    public CustomerCareService getCustomerCareServiceImplPort(WebServiceFeature... features) {
        return super.getPort(CustomerCareServiceImplPort, CustomerCareService.class, features);
    }

}
