
package stubs.customerCare;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-04-07T15:20:57.813+02:00
 * Generated source version: 3.1.10
 */

@WebFault(name = "UnknownOrderId", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/tcf/customer-care")
public class UnknownOrderId_Exception extends Exception {
    
    private stubs.customerCare.UnknownOrderId unknownOrderId;

    public UnknownOrderId_Exception() {
        super();
    }
    
    public UnknownOrderId_Exception(String message) {
        super(message);
    }
    
    public UnknownOrderId_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public UnknownOrderId_Exception(String message, stubs.customerCare.UnknownOrderId unknownOrderId) {
        super(message);
        this.unknownOrderId = unknownOrderId;
    }

    public UnknownOrderId_Exception(String message, stubs.customerCare.UnknownOrderId unknownOrderId, Throwable cause) {
        super(message, cause);
        this.unknownOrderId = unknownOrderId;
    }

    public stubs.customerCare.UnknownOrderId getFaultInfo() {
        return this.unknownOrderId;
    }
}
